name: ecommerce_mobile_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  #Internationalization
  intl: ^0.20.2

  #Network
  dio: ^5.7.0
  retrofit: 4.7.3

  #UI
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0

  #Architecture
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  get_it: ^8.0.1
  injectable: ^2.5.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  #Logger
  pretty_dio_logger: ^1.4.0
  logger: ^2.5.0

  #Storage
  shared_preferences: ^2.3.3

  #Security
  flutter_secure_storage: ^9.2.3

  #Util
  dartz: ^0.10.1
  cupertino_icons: ^1.0.8

  #Routing
  go_router: ^15.0.0

  #Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  firebase_messaging: ^15.2.7
  firebase_analytics: ^11.5.0
  firebase_crashlytics: ^4.3.7
  google_sign_in: ^6.2.1

  #local_notification
  flutter_local_notifications: ^19.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  build_runner: ^2.4.14
  retrofit_generator: ^9.7.0
  json_serializable: ^6.9.3
  freezed: ^2.5.8
  flutter_gen_runner: ^5.11.0

flutter_gen:
  output: lib/core/assets_gen/ # Optional (default: lib/gen/)
  line_length: 80
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Bold.ttf
        - asset: assets/fonts/CircularStd-Book.ttf
        - asset: assets/fonts/CircularStd-Medium.ttf
  #         style: italic
    - family: Gabarito
      fonts:
        - asset: assets/fonts/Gabarito-Bold.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
